after 3 years, add uncommited and modified scripts
  @ 00:05 hs

diff --git a/redmine-from-jrnl b/redmine-from-jrnl
--- a/redmine-from-jrnl
+++ b/redmine-from-jrnl
@@ -24,36 +24,15 @@ die ()
 CONFIG="$HOME/.redmine.conf"
 [[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"
 
-eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$CONFIG" | while read -r key val
-do
-    str="$key='$val'"
-    echo "$str"
-done)
+ISSUE=$(redmine-add-comment-from-jrnl | egrep -o "#[0-9]+\ " | head -1)
+OK=$?
+[[ "$OK" -ne 0 ]] && die "error when add comment"
+[[ -z "$ISSUE" ]] && die "empty ISSUE"
 
-[[ -z "$API_URL" ]] && die "empty URL"
-[[ -z "$API_KEY" ]] && die "empty KEY"
+ISSUE_ID=$(echo "$ISSUE" | egrep -o "[0-9]+" | head -1)
+[[ -z "$ISSUE" ]] && die "empty ISSUE_ID"
 
-[[ -z "$1" ]] && die "empty ISSUE_ID"
-ISSUE_ID="$1"
+VALID_ISSUE_ID=$(echo "$ISSUE_ID" | egrep -o "^[0-9]+$" | head -1)
+[[ "$VALID_ISSUE_ID" != "$ISSUE_ID" ]] && die "invalid ISSUE_ID"
 
-[[ -z "$2" ]] && die "empty PARENT_ID"
-PARENT_ID="$2"
-
-JSON_FILE='/tmp/new.json'
-
-JSON=$(cat << EOF
-{
-    "issue": {
-      "parent_issue_id": $PARENT_ID
-    }
-}
-EOF
-)
-
-echo "$JSON" > "$JSON_FILE"
-
-H1='"Content-Type: application/json"'
-H2='"X-Redmine-API-Key: '$API_KEY'"'
-URL="$API_URL/issues/${ISSUE_ID}.json"
-
-echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
+redmine-time-entry-from-jrnl
diff --git a/redmine-get-project b/redmine-get-project
--- a/redmine-get-project
+++ b/redmine-get-project
@@ -24,6 +24,16 @@ die ()
 CONFIG="$HOME/.redmine.conf"
 [[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"
 
+API_CACHE="$HOME/.cache/$(basename "$0")"
+UA='Mozilla/5.0 (X11; Linux x86_64; rv:70) Gecko/20100101 Firefox/70'
+
+for b in curl jq
+do
+  which $b 2>/dev/null >/dev/null
+  OK="$?"
+  [[ "$OK" -ne 0 ]] && die "not found: $b try: sudo apt-get install $b"
+done
+
 eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$CONFIG" | while read -r key val
 do
     str="$key='$val'"
@@ -34,39 +44,35 @@ done)
 [[ -z "$API_KEY" ]] && die "empty KEY"
 
 [[ -z "$1" ]] && die "empty ISSUE_ID"
-ISSUE_ID="$1"
-
-[[ -z "$2" ]] && die "empty NOTES"
-
-NOTES=$(
-echo "$2"                           \
-  | expand -t 2                     \
-  | sed 's/"/\\"/g'                 \
-  | sed 's/\x1B\[[0-9;]*[JKmsu]//g' \
-  | sed ':a;N;$!ba;s/\n/\\n/g'      \
-  | sed -e 's/\r//g'
-)
-
-  #| tr '"' "'"                      \
-JSON_FILE='/tmp/new.json'
-
-JSON=$(cat << EOF
-{
-    "issue": {
-      "notes": "$NOTES"
-    }
-}
-EOF
-)
-
-echo "$JSON" > "$JSON_FILE"
+ISSUE_ID="$(echo "$1" | tr -d '#')"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues/${ISSUE_ID}.json"
-echo "#$ISSUE_ID $NOTES" | cut -d'\' -f1
 
-CURL_PROXY=''
-[[ ! -z "$REDMINE_PROXY_SOCKS" ]] && CURL_PROXY="--socks5 $REDMINE_PROXY_SOCKS"
-# FIXME verify https_proxy
-echo curl $CURL_PROXY -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
+JQ=$(cat  << EOF
+.issue.project.name
+EOF
+)
+
+read_cache()
+{
+  [[ ! -e "$API_CACHE" ]] && touch "$API_CACHE"
+  grep -w "$1" "$API_CACHE" | cut -d'|' -f2-
+}
+
+fetch()
+{
+  CURL="curl -s -k -H "$H1" -X GET -H "$H2""
+  JSON="$(echo "$CURL" "$URL" | bash | jq -r "$JQ")"
+  echo "$URL|$JSON" >> "$API_CACHE"
+}
+
+CACHE="$(read_cache "$URL")"
+
+if [[ ! -z "$CACHE" ]]
+then
+  echo "$CACHE"
+else
+  fetch "$URL"
+fi
diff --git a/redmine-get-status b/redmine-get-status
--- a/redmine-get-status
+++ b/redmine-get-status
@@ -24,6 +24,13 @@ die ()
 CONFIG="$HOME/.redmine.conf"
 [[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"
 
+for b in curl jq
+do
+  which $b 2>/dev/null >/dev/null
+  OK="$?"
+  [[ "$OK" -ne 0 ]] && die "not found: $b try: sudo apt-get install $b"
+done
+
 eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$CONFIG" | while read -r key val
 do
     str="$key='$val'"
@@ -36,37 +43,12 @@ done)
 [[ -z "$1" ]] && die "empty ISSUE_ID"
 ISSUE_ID="$1"
 
-[[ -z "$2" ]] && die "empty NOTES"
-
-NOTES=$(
-echo "$2"                           \
-  | expand -t 2                     \
-  | sed 's/"/\\"/g'                 \
-  | sed 's/\x1B\[[0-9;]*[JKmsu]//g' \
-  | sed ':a;N;$!ba;s/\n/\\n/g'      \
-  | sed -e 's/\r//g'
-)
-
-  #| tr '"' "'"                      \
-JSON_FILE='/tmp/new.json'
-
-JSON=$(cat << EOF
-{
-    "issue": {
-      "notes": "$NOTES"
-    }
-}
-EOF
-)
-
-echo "$JSON" > "$JSON_FILE"
-
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues/${ISSUE_ID}.json"
-echo "#$ISSUE_ID $NOTES" | cut -d'\' -f1
 
-CURL_PROXY=''
-[[ ! -z "$REDMINE_PROXY_SOCKS" ]] && CURL_PROXY="--socks5 $REDMINE_PROXY_SOCKS"
-# FIXME verify https_proxy
-echo curl $CURL_PROXY -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
+JQ='.issue.status.name'
+
+echo curl -s -k -H "$H1" -X GET -H "$H2" "$URL" \
+  | bash \
+  | jq -r "$JQ"
