Refactor redmine-new-issue
* Fix parent_id
* Load default variables
* Add enviroment variables
* Sanity Subject and Description
* Allow username or assigned_to_id
* Add color for error messages

@ 01:00 hs

diff --git a/redmine-new-issue b/redmine-new-issue
--- a/redmine-new-issue
+++ b/redmine-new-issue
@@ -18,7 +18,7 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
@@ -37,26 +37,60 @@ done)
 [[ -z "$API_KEY" ]] && die "empty KEY"
 
 [[ -z "$1" ]] && die "empty SUBJECT"
-SUBJECT="$1"
+SUBJECT=$(echo "$1" | tr '"' "'" | sed 's/\x1B\[[0-9;]*[JKmsu]//g')
 
-[[ ! -z "$DEFAULT_PRIORITY_ID" ]]    && PRIORITY_ID=$DEFAULT_PRIORITY_ID
-[[ ! -z "$DEFAULT_PROJECT_ID" ]]     && PROJECT_ID=$DEFAULT_PROJECT_ID
-[[ ! -z "$DEFAULT_ASSIGNED_TO_ID" ]] && ASSIGNED_TO_ID=$DEFAULT_ASSIGNED_TO_ID
-[[ ! -z "$DEFAULT_CATEGORY_ID" ]]    && CATEGORY_ID=$DEFAULT_CATEGORY_ID
-[[ ! -z "$DEFAULT_STATUS_ID" ]]      && STATUS_ID=$DEFAULT_STATUS_ID
-[[ ! -z "$DEFAULT_TRACKER_ID" ]]     && TRACKER_ID=$DEFAULT_TRACKER_ID
+# load default variables
+[[ ! -z "$DEFAULT_PRIORITY_ID" ]]    && PRIORITY_ID="$DEFAULT_PRIORITY_ID"
+[[ ! -z "$DEFAULT_PROJECT_ID" ]]     && PROJECT_ID="$DEFAULT_PROJECT_ID"
+[[ ! -z "$DEFAULT_ASSIGNED_TO_ID" ]] && ASSIGNED_TO_ID="$DEFAULT_ASSIGNED_TO_ID"
+[[ ! -z "$DEFAULT_CATEGORY_ID" ]]    && CATEGORY_ID="$DEFAULT_CATEGORY_ID"
+[[ ! -z "$DEFAULT_STATUS_ID" ]]      && STATUS_ID="$DEFAULT_STATUS_ID"
+[[ ! -z "$DEFAULT_TRACKER_ID" ]]     && TRACKER_ID="$DEFAULT_TRACKER_ID"
 
-DESCRIPTION=''
-[[ ! -z "$2" ]] && DESCRIPTION="$2"
+# enviroment variables overwrite default variables
+[[ ! -z "$REDMINE_ASSIGNED_TO_ID" ]] && ASSIGNED_TO_ID="$REDMINE_ASSIGNED_TO_ID"
+[[ ! -z "$REDMINE_CATEGORY_ID" ]]    && CATEGORY_ID="$REDMINE_CATEGORY_ID"
+[[ ! -z "$REDMINE_PARENT_ID" ]]      && PARENT_ID="$REDMINE_PARENT_ID"
+[[ ! -z "$REDMINE_PRIORITY_ID" ]]    && PRIORITY_ID="$REDMINE_PRIORITY_ID"
+[[ ! -z "$REDMINE_PROJECT_ID" ]]     && PROJECT_ID="$REDMINE_PROJECT_ID"
+[[ ! -z "$REDMINE_STATUS_ID" ]]      && STATUS_ID="$REDMINE_STATUS_ID"
+[[ ! -z "$REDMINE_TRACKER_ID" ]]     && TRACKER_ID="$REDMINE_TRACKER_ID"
+
+if [ -z "$2" ]
+then
+  DESCRIPTION=''
+else
+  DESCRIPTION=$(
+  echo "$2" \
+    | tr '"' "'" \
+    | sed 's/\x1B\[[0-9;]*[JKmsu]//g' \
+    | sed ':a;N;$!ba;s/\n/\\n/g'
+  )
+fi
+
+# argument variables overwrite enviroment variables
 [[ ! -z "$3" ]] && PRIORITY_ID="$3"
-[[ ! -z "$4" ]] && ASSIGNED_TO_ID="$4"
+
+# allow username or user_id
+if [ ! -z "$4" ]
+then
+  VALID_USER_ID=$(echo "$4" | egrep "^[0-9]+$")
+  if [ "$VALID_USER_ID" = "$4" ]
+  then
+    ASSIGNED_TO_ID="$4"
+  else
+    U=$(echo "$4" | tr '[:lower:]' '[:upper:]')
+    ID=$(egrep "^($U):" "$CONFIG" | cut -d: -f2 | egrep -o "[0-9]+")
+    [[ -z "$ID" ]] && die "invalid USERNAME"
+    ASSIGNED_TO_ID="$ID"
+  fi
+fi
+
 [[ ! -z "$5" ]] && PARENT_ID="$5"
 [[ ! -z "$6" ]] && PROJECT_ID="$6"
 
 [[ "$PRIORITY_ID" -lt "$PRIORITY_MIN_ID" ]] && die "invalid PRIORITY_ID"
 [[ "$PRIORITY_ID" -gt "$PRIORITY_MAX_ID" ]] && die "invalid PRIORITY_ID"
-
-VALID_ASSIGNED_LOGIN=$(echo "$4" | egrep "^[a-zA-Z]+$")
 
 [[ ! "$PROJECT_ID" =~ "$NUMBER" ]] && die "invalid PROJECT_ID"
 
@@ -88,8 +122,7 @@ JSON=$(cat << EOF
       "assigned_to_id": $ASSIGNED_TO_ID,
       "status_id": $STATUS_ID,
       "tracker_id": $TRACKER_ID,
-      "parent_id": $PARENT_ID,
-      "root_id": $PARENT_ID,
+      "parent_issue_id": $PARENT_ID,
       "description": "$DESCRIPTION"
     }
 }
@@ -97,13 +130,13 @@ EOF
 )
 fi
 
-echo $JSON >$JSON_FILE
+echo "$JSON" > "$JSON_FILE"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues.json"
 
-echo curl -s -k -H "$H1" -X POST --data "@$JSON_FILE" -H "$H2" $URL \
+echo curl -s -k -H "$H1" -X POST --data "@$JSON_FILE" -H "$H2" "$URL" \
     | bash \
     | python -mjson.tool \
     | egrep '"id"' \
