Refactor all scripts, add support for add comment/time-entry from jrnl/git/file
@ 03:00 hs

diff --git a/redmine-add-comment b/redmine-add-comment
--- a/redmine-add-comment
+++ b/redmine-add-comment
@@ -18,7 +18,7 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
@@ -40,7 +40,14 @@ done)
 ISSUE_ID="$1"
 
 [[ -z "$2" ]] && die "empty NOTES"
-NOTES="$2"
+
+NOTES=$(
+echo "$2" \
+  | tr '"' "'" \
+  | sed 's/\x1B\[[0-9;]*[JKmsu]//g' \
+  | sed ':a;N;$!ba;s/\n/\\n/g' \
+  | sed -e 's/\r//g'
+)
 
 JSON_FILE='/tmp/new.json'
 
@@ -53,10 +60,10 @@ JSON=$(cat << EOF
 EOF
 )
 
-echo "$JSON" >$JSON_FILE
+echo "$JSON" > "$JSON_FILE"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues/${ISSUE_ID}.json"
-
-echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" $URL | bash
+echo "#$ISSUE_ID $NOTES" | cut -d'\' -f1
+echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
diff --git a/redmine-assign-to b/redmine-assign-to
--- a/redmine-assign-to
+++ b/redmine-assign-to
@@ -18,7 +18,7 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
@@ -39,11 +39,24 @@ done)
 [[ ! -z "$DEFAULT_ASSIGNED_TO_ID" ]] && ASSIGNED_TO_ID="$DEFAULT_ASSIGNED_TO_ID"
 
 [[ -z "$1" ]] && die "empty ISSUE_ID"
+VALID_ISSUE_ID=$(echo "$1" | egrep "^[0-9]+$")
+
+[[ "$VALID_ISSUE_ID" != "$1" ]] && die "invalid ISSUE_ID"
 ISSUE_ID="$1"
 
-[[ ! -z "$2" ]] && ASSIGNED_TO_ID="$2"
-
-# FIXME validate ASSIGNED_TO_ID
+if [ ! -z "$2" ]
+then
+  VALID_USER_ID=$(echo "$2" | egrep "^[0-9]+$")
+  if [ "$VALID_USER_ID" = "$2" ]
+  then
+    ASSIGNED_TO_ID="$2"
+  else
+    U=$(echo "$2" | tr '[:lower:]' '[:upper:]')
+    ID=$(egrep "^($U):" "$CONFIG" | cut -d: -f2 | egrep -o "[0-9]+")
+    [[ -z "$ID" ]] && die "invalid USERNAME"
+    ASSIGNED_TO_ID="$ID"
+  fi
+fi
 
 JSON_FILE='/tmp/new.json'
 
diff --git a/redmine-autoclose b/redmine-autoclose
--- a/redmine-autoclose
+++ b/redmine-autoclose
@@ -18,7 +18,7 @@
 
 die ()
 {
-echo "ERROR $1" && exit 1
+echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 sql_get_user_id ()
@@ -204,16 +204,15 @@ $PROGRAM --mycnf ~/.my.cnf
 EOF
 )
 
-[[ $err -ne 0 ]] && die "Invalid: $COMMAND $EXAMPLE"
+[[ $err -ne 0 ]] && die "Invalid: $* $EXAMPLE"
 }
 
 GETOPT='getopt'
 PROGRAM="${0##*/}"
-COMMAND="$@"
 
 init "$@"
 
-DATE=`date +%Y-%m-%d\ %H:%M`
+DATE=$(date +%Y-%m-%d\ %H:%M)
 echo "date: $DATE"
 
 [[ -z "$MYCNF" ]] && MYCNF=$HOME'/.my.cnf'
@@ -224,30 +223,30 @@ MYSQL="mysql --defaults-file=$MYCNF -N"
 [[ -z $USER_NAME ]] && USER_NAME="mr.robot"
 echo "user_name: $USER_NAME"
 
-USER_ID=`sql_get_user_id "$USER_NAME" | $MYSQL`
+USER_ID=$(sql_get_user_id "$USER_NAME" | $MYSQL)
 [[ -z $USER_ID ]] && die "no valid user_id for $USER_NAME"
 echo "user_id: $USER_ID"
 
 [[ -z $PROJECT_NAME ]] && die "no valid project_name"
 echo "project_name: $PROJECT_NAME"
 
-PROJECT_ID=`sql_get_project_id "$PROJECT_NAME" | $MYSQL`
+PROJECT_ID=$(sql_get_project_id "$PROJECT_NAME" | $MYSQL)
 [[ -z $PROJECT_ID ]] && die "no valid project_id"
 echo "project_id: $PROJECT_ID"
 
 echo "from_status: $FROM_STATUS"
-FROM_STATUS_ID=`sql_get_status_id "$FROM_STATUS" | $MYSQL`
+FROM_STATUS_ID=$(sql_get_status_id "$FROM_STATUS" | $MYSQL)
 [[ -z $FROM_STATUS_ID ]] && die "no valid id for $FROM_STATUS"
 echo "from_status_id: $FROM_STATUS_ID"
 
 echo "to_status: $TO_STATUS"
-TO_STATUS_ID=`sql_get_status_id "$TO_STATUS" | $MYSQL`
+TO_STATUS_ID=$(sql_get_status_id "$TO_STATUS" | $MYSQL)
 [[ -z $TO_STATUS_ID ]] && die "no valid id for $TO_STATUS"
 echo "to_status_id: $TO_STATUS_ID"
 
 [[ -z $DAYS ]] && die "no valid days"
 
-WEEKDAY=`date +%u`
+WEEKDAY=$(date +%u)
 
 [[ "$WEEKDAY" -eq 6 ]] && DAYS=$((DAYS+1))
 [[ "$WEEKDAY" -eq 7 ]] && DAYS=$((DAYS+2))
@@ -260,7 +259,7 @@ UPDATE=/tmp/issues.redmine.sql
 ISSUES=/tmp/issues.redmine.log
 
 sql_get_issues | $MYSQL >"$ISSUES"
-TOTAL=`wc -l "$ISSUES" | awk '{print $1}'`
+TOTAL=$(wc -l "$ISSUES" | awk '{print $1}')
 echo "total issues: $TOTAL"
 
 [[ "$TOTAL" -eq 0 ]] && die "nothing to do :)"
@@ -275,40 +274,40 @@ awk '{print $1}' "$ISSUES" | while read i
 do
     if [ "$FROM_STATUS_ID" = "$TO_STATUS_ID" ]
     then
-        FROM_PRIORITY_ID=`sql_get_issue_priority_id $i | $MYSQL`
+        FROM_PRIORITY_ID=$(sql_get_issue_priority_id "$i" | $MYSQL)
         [[ -z "$FROM_PRIORITY_ID" ]] && die "empty FROM_PRIORITY_ID"
 
-        FROM_PRIORITY=`sql_get_priority $FROM_PRIORITY_ID | $MYSQL`
+        FROM_PRIORITY=$(sql_get_priority "$FROM_PRIORITY_ID" | $MYSQL)
         [[ -z "$FROM_PRIORITY" ]] && die "empty FROM_PRIORITY"
 
-        FROM_POSITION=`sql_get_priority_position $FROM_PRIORITY_ID | $MYSQL`
+        FROM_POSITION=$(sql_get_priority_position "$FROM_PRIORITY_ID" | $MYSQL)
         [[ -z "$FROM_POSITION" ]] && die "empty from_position"
 
-        TO_POSITION=$[ $FROM_POSITION + 1]
-        MAX_POSITION=`sql_get_max_priority_postition | $MYSQL`
+        TO_POSITION=$((FROM_POSITION + 1))
+        MAX_POSITION=$(sql_get_max_priority_postition | $MYSQL)
         [[ -z "$MAX_POSITION" ]] && die "empty max_position"
 
-        if [ $TO_POSITION -gt $MAX_POSITION ]
+        if [ "$TO_POSITION" -gt "$MAX_POSITION" ]
         then
             TO_POSITION=$MAX_POSITION
         fi
 
         [[ -z "$TO_POSITION" ]] && die "empty to_position"
 
-        TO_PRIORITY_ID=`sql_get_priority_by_position $TO_POSITION | $MYSQL`
+        TO_PRIORITY_ID=$(sql_get_priority_by_position "$TO_POSITION" | $MYSQL)
         [[ -z "$TO_PRIORITY_ID" ]] && die "empty TO_PRIORITY_ID"
 
-        TO_PRIORITY=`sql_get_priority $TO_PRIORITY_ID | $MYSQL`
+        TO_PRIORITY=$(sql_get_priority "$TO_PRIORITY_ID" | $MYSQL)
         [[ -z "$TO_PRIORITY" ]] && die "empty TO_PRIORITY"
 
         NOTES="After $DAYS of inactivity, change priority from: $FROM_PRIORITY to: $TO_PRIORITY"
 
-        if [ $FROM_PRIORITY_ID -eq $TO_PRIORITY_ID ]
+        if [ "$FROM_PRIORITY_ID" -eq "$TO_PRIORITY_ID" ]
         then
             continue
         else
-            echo "$i "$NOTES
-            sql_update_priority "$i" $TO_PRIORITY_ID >>$UPDATE
+            echo "$i $NOTES"
+            sql_update_priority "$i" "$TO_PRIORITY_ID" >>$UPDATE
             sql_insert_journal "$i" >>"$UPDATE"
         fi
     else
@@ -319,7 +318,7 @@ done
 
 [[ ! -e "$UPDATE" ]] && die "no valid $UPDATE"
 
-T=`wc -l "$UPDATE" | awk '{print $1}'`
+T=$(wc -l "$UPDATE" | awk '{print $1}')
 
 [[ "$T" -eq 0 ]] && die "empty file $UPDATE"
 
diff --git a/redmine-delete-timer b/redmine-delete-timer
--- a/redmine-delete-timer
+++ b/redmine-delete-timer
@@ -18,7 +18,7 @@
 
 die ()
 {
-echo "ERROR $1" && exit 1
+echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 sql_get_user_id ()
@@ -136,7 +136,7 @@ COMMAND="$@"
 
 init "$@"
 
-DATE=`date +%Y-%m-%d\ %H:%M`
+DATE=$(date +%Y-%m-%d\ %H:%M)
 echo "date: $DATE"
 
 [[ -z "$MYCNF" ]] && MYCNF=$HOME'/.my.cnf'
@@ -147,21 +147,20 @@ MYSQL="mysql --defaults-file=$MYCNF -N"
 [[ -z $USER_NAME ]] && USER_NAME="mr.robot"
 echo "user_name: $USER_NAME"
 
-USER_ID=`sql_get_user_id "$USER_NAME" | $MYSQL`
+USER_ID=$(sql_get_user_id "$USER_NAME" | $MYSQL)
 [[ -z $USER_ID ]] && die "no valid user_id for $USER_NAME"
 echo "user_id: $USER_ID"
 
-UPDATE=/tmp/issues.redmine.sql
 TMP=/tmp/tmp.redmine.log
 
-sql_get_time_trackers $USER_ID | $MYSQL | tee $TMP
-TOTAL_TRACKERS=`wc -l $TMP | awk '{print $1}'`
+sql_get_time_trackers "$USER_ID" | $MYSQL | tee "$TMP"
+TOTAL_TRACKERS=$(wc -l "$TMP" | awk '{print $1}')
 echo "total trackers: $TOTAL_TRACKERS"
 
-sql_get_time_entries $USER_ID | $MYSQL | tee $TMP
-TOTAL_ENTRIES=`wc -l $TMP | awk '{print $1}'`
+sql_get_time_entries "$USER_ID" | $MYSQL | tee "$TMP"
+TOTAL_ENTRIES=$(wc -l "$TMP" | awk '{print $1}')
 echo "total entries: $TOTAL_ENTRIES"
 
-[[ "$TOTAL_TRACKERS" -gt 0 ]] && sql_delete_time_trackers $USER_ID | $MYSQL
-[[ "$TOTAL_ENTRIES" -gt 0 ]] && sql_delete_time_entries $USER_ID | $MYSQL
+[[ "$TOTAL_TRACKERS" -gt 0 ]] && sql_delete_time_trackers "$USER_ID" | $MYSQL
+[[ "$TOTAL_ENTRIES" -gt 0 ]] && sql_delete_time_entries "$USER_ID" | $MYSQL
 
diff --git a/redmine-fix b/redmine-fix
--- a/redmine-fix
+++ b/redmine-fix
@@ -18,7 +18,7 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
@@ -67,10 +67,10 @@ EOF
 )
 fi
 
-echo $JSON >$JSON_FILE
+echo "$JSON" > "$JSON_FILE"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues/${ISSUE_ID}.json"
 
-echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" $URL | bash
+echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
diff --git a/redmine-get-spent_hours b/redmine-get-spent_hours
--- a/redmine-get-spent_hours
+++ b/redmine-get-spent_hours
@@ -24,6 +24,13 @@ die ()
 CONFIG="$HOME/.redmine.conf"
 [[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"
 
+for b in curl jq
+do
+  which $b 2>/dev/null >/dev/null
+  OK="$?"
+  [[ "$OK" -ne 0 ]] && die "not found: $b try: sudo apt-get install $b"
+done
+
 export http_proxy=""
 export https_proxy=""
 
@@ -36,30 +43,20 @@ done)
 [[ -z "$API_URL" ]] && die "empty URL"
 [[ -z "$API_KEY" ]] && die "empty KEY"
 
-[[ ! -z "$DEFAULT_PROJECT_ID" ]] && PROJECT_ID="$DEFAULT_PROJECT_ID"
-
 [[ -z "$1" ]] && die "empty ISSUE_ID"
 ISSUE_ID="$1"
-
-[[ ! -z "$2" ]] && PROJECT_ID="$2"
-
-# FIXME validate PROJECT_ID
-
-JSON_FILE='/tmp/new.json'
-
-JSON=$(cat << EOF
-{
-    "issue": {
-      "project_id": $PROJECT_ID
-    }
-}
-EOF
-)
-
-echo "$JSON" >"$JSON_FILE"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/issues/${ISSUE_ID}.json"
 
-echo curl -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash
+JQ=$(cat  << EOF
+{
+spent_hours: .issue.spent_hours,
+}
+EOF
+)
+
+echo
+echo curl -s -k -H "$H1" -X GET -H "$H2" "$URL" | bash | jq ". | $JQ" | grep spent_hours | cut -d: -f2
+
diff --git a/redmine-show-issue b/redmine-show-issue
--- a/redmine-show-issue
+++ b/redmine-show-issue
@@ -18,7 +18,7 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
@@ -27,7 +27,7 @@ CONFIG="$HOME/.redmine.conf"
 for b in curl jq
 do
   which $b 2>/dev/null >/dev/null
-  OK=$(echo $?)
+  OK="$?"
   [[ "$OK" -ne 0 ]] && die "not found: $b try: sudo apt-get install $b"
 done
 
@@ -53,6 +53,7 @@ URL="$API_URL/issues/${ISSUE_ID}.json"
 JQ=$(cat  << EOF
 {
 issue: .issue.id,
+parent: .issue.parent,
 tracker: .issue.tracker.name,
 status: .issue.status.name,
 priority: .issue.priority.name,
@@ -67,5 +68,10 @@ EOF
 )
 
 echo
-echo curl -s -k -H "$H1" -X GET -H "$H2" "$URL" | bash | jq ". | $JQ"
+echo curl -s -k -H "$H1" -X GET -H "$H2" "$URL" \
+  | bash \
+  | jq ". | $JQ" \
+  | sed 's/\\r\\n/\n/g' \
+  | sed 's/\\t/\t/g'
+
 
diff --git a/redmine-time-entry b/redmine-time-entry
--- a/redmine-time-entry
+++ b/redmine-time-entry
@@ -18,22 +18,31 @@
 
 die ()
 {
-  echo "ERROR $1" && exit 1
+  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
 }
 
 CONFIG="$HOME/.redmine.conf"
 [[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"
 
-[[ -z "$1" ]] && die "empty ISSUE_ID"
-[[ -z "$2" ]] && die "empty MINUTES"
+[[ -z "$1" ]] && die "empty MINUTES"
+[[ -z "$2" ]] && die "empty ISSUE_ID"
 [[ -z "$3" ]] && die "empty COMMENTS"
 
-ISSUE_ID="$1"
-MINUTES="$2"
-HOURS=`echo "scale = 10;$MINUTES/60" | bc | awk '{printf "%0.2f",$1}'`
+VALID_MINUTES=$(echo "$1" | egrep -o "^[0-9]+$")
+[[ "$VALID_MINUTES" != "$1" ]] && die "invalid MINUTES: $MINUTES"
+MINUTES="$1"
 
-COMMENTS="$3"
-SPENT_ON=`date +%Y-%m-%d`
+ISSUE_ID=$(echo "$2" | egrep -o "^[0-9]+$")
+HOURS=$(echo "scale = 10;$MINUTES/60" | bc | awk '{printf "%0.2f",$1}')
+
+COMMENTS=$(
+echo "$3" \
+  | tr '"' "'" \
+  | sed 's/\x1B\[[0-9;]*[JKmsu]//g' \
+  | sed ':a;N;$!ba;s/\n/\\n/g'
+)
+
+SPENT_ON=$(date +%Y-%m-%d)
 
 export http_proxy=""
 export https_proxy=""
@@ -62,13 +71,13 @@ JSON=$(cat << EOF
 EOF
 )
 
-echo $JSON >$JSON_FILE
+echo "$JSON" > "$JSON_FILE"
 
 H1='"Content-Type: application/json"'
 H2='"X-Redmine-API-Key: '$API_KEY'"'
 URL="$API_URL/time_entries.json"
-
-echo curl -s -k -H "$H1" -X POST --data "@$JSON_FILE" -H "$H2" $URL \
+echo "$MINUTES #$ISSUE_ID '$COMMENTS'"
+echo curl -s -k -H "$H1" -X POST --data "@$JSON_FILE" -H "$H2" "$URL" \
     | bash \
     | python -mjson.tool | egrep "(hours|created)"
 
